---
nginx_vhosts:
  - listen: "80"
    server_name: "drupal.loc"
    root: "/var/www/drupal"
    index: "index.php index.html index.htm"
    error_page: "500 500.html"
    access_log: "/var/log/drupal.access.log"
    error_log: "/var/log/drupal.error.log"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }