php_timezone: Europe/Moscow
php_upload_max_filesize: "20M"
php_post_max_size: "20M"
php_memory_limit: "1024M"

debian_php7_apt_repo: "http://packages.dotdeb.org"
debian_php7_apt_key: "https://www.dotdeb.org/dotdeb.gpg"
ubuntu_php7_ppa_repo: "ppa:ondrej/php"

apt_php_packages:
  - php7.0
  - php7.0-cgi
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-fpm
  - php7.0-gd
  - php7.0-intl
  - php7.0-json
  - php7.0-mysql
  - php7.0-mbstring
  - php7.0-xml
  - php7.0-simplexml
  - php7.0-pgsql
  - php7.0-zip


php_owner: www-data
php_group: www-data
