- hosts: all

  roles:
    - azavea.unzip
    - hashbangcode.sendmail
    - geerlingguy.git
    - geerlingguy.nginx
    - chusiang.php7
    - geerlingguy.composer
    - adv.drush
    - ANXS.postgresql

  vars_files:
    - vars/nginx.yml
    - vars/drupal.yml
    - vars/php7.yml
    - vars/postgresql.yml
    - vars/git.yml

  tasks:

    - name: Check out Drupal Core to the default location.
      git:
        repo: "{{ drupal_repo_url }}"
        version: "{{ drupal_core_version }}"
        update: "{{ drupal_keep_updated }}"
        dest: "{{ drupal_core_path }}"

    - name: Install drupal composer dependencies.
      command: >
        composer install
        chdir={{ drupal_core_path }}

    - name: Check if site is already installed.
      command: >
        /usr/local/bin/drush status bootstrap
        chdir={{ drupal_core_path }}
      register: drupal_site_installed
      failed_when: false
      changed_when: false

    - name: Download profiles.
      command: >
        drush dl -y {{ drupal_download_profiles | join(" ") }}
        chdir={{ drupal_core_path }}
      when: "drupal_download_profiles is defined and 'Successful' not in drupal_site_installed.stdout"

    - name: Install Drupal with drush.
      command: >
        drush si {{ drupal_install_profile }} -y
        --site-name="{{ drupal_site_name }}"
        --account-name={{ drupal_admin_name }}
        --account-pass={{ drupal_admin_password}}
        --db-url=pgsql://{{ drupal_db_user }}:{{ drupal_db_password }}@localhost/{{ drupal_db_name }}
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/default/settings.php
      when: "'Successful' not in drupal_site_installed.stdout"

    - name: Set permissions properly on settings.php.
      file:
        path: "{{ drupal_core_path }}/sites/default/settings.php"
        mode: 0744

    - name: Set permissions properly on files directory.
      file:
        path: "{{ drupal_core_path }}/sites/default/files"
        mode: 0777
        state: directory
        recurse: yes

    - name: Install configured modules with drush.
      command: >
        /usr/local/bin/drush pm-enable -y {{ drupal_enable_modules | join(" ") }}
        chdir={{ drupal_core_path }}
      when: "'Successful' not in drupal_site_installed.stdout and drupal_enable_modules is defined"