- hosts: all

  roles:
    - geerlingguy.git
    - geerlingguy.nginx
    - chusiang.php7
    - geerlingguy.composer
    - ANXS.postgresql

  vars_files:
    - vars/nginx.yml
    - vars/php7.yml
    - vars/postgresql.yml
    - vars/git.yml

  tasks:
    - file: path=/var/www state=directory mode=0755
      name: create /var/www
    - composer:
        command: "create-project"
        arguments: "drupal/drupal drupal 8.1.*"
        working_dir: "/var/www/"
        prefer_dist: "yes"
      name: Install drupal throw composer