---
- src: chusiang.php7
- src: https://github.com/ANXS/postgresql.git
  version: v1.6.2
  name: ANXS.postgresql
- src: geerlingguy.nginx
- src: geerlingguy.composer
- src: geerlingguy.git
- src: git+https://scm.adv.ru/scm/izv/adv.drush.git
  version: master
  name: adv.drush
  path: roles
- src: azavea.unzip